name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cashe: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Update NPM
      run: npm install -g npm@9.3.1
    - name: Build
      run: npm start
    - name: Test
      run: npm run test