name: CI/CD_new

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cashe: 'npm'
    - name: Install dependencies and make test-coverage
      run: | 
        npm ci
        make test-coverage
    - name: Build
      run: npm run build --if-present
    - name: start up th server
      run: npm start
    - name: Test
      run: npm run test