name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cashe: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm start
    - name: Test
      run: npm run test